name: eCommerce
services:
  
  catalog.db:
    image: postgres
    container_name: catalog.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
  
  basket.db:
    image: postgres
    container_name: basket.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data

  distributed.cache:
    image: redis
    container_name: distributed.cache
    restart: always
    ports:
      - "6379:6379"
        
  ordering.db:
    image: mcr.microsoft.com/mssql/server
    container_name: ordering.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=OrderingSa2316
    restart: always
    ports:
      - "6433:1433"
  
  catalog.api:
    container_name: catalog.api
    image: catalog.api
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    ports:
      - "6000:8080"
      - "6060:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__CatalogDb=Server=catalog.db;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1q2w3e
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - catalog.db
    volumes:
      - ~/.aspnet/https:/https:ro
  
  basket.api:
    container_name: basket.api
    image: basket.api
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile
    ports:
      - "6001:8080"
      - "6061:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__BasketDb=Server=basket.db;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;
      - ConnectionStrings__Redis=distributed.cache:6379
      - DiscountGrpc__Url=https://discount.grpc:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1q2w3e
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - basket.db
      - distributed.cache
      - discount.grpc
    volumes:
      - ~/.aspnet/https:/https:ro

  discount.grpc:
    container_name: discount.grpc
    image: discount.grpc
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile
    ports:
      - "6002:8080"
      - "6062:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DiscountDb=Data Source=DiscountDb;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1q2w3e
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

volumes:
  postgres_catalog:
  postgres_basket: